### ISSUE TITLE
System.MissingMethodException: Method not found: ‘Void AngleSharp.Dom.IElement.RemoveAttribute(System.String)’.

### ISSUE THREAD

**Issue by JamesNK** [milkshakesoftware/PreMailer.Net#130]
There is a breaking change in AngleSharp 0.9.9: https://github.com/AngleSharp/AngleSharp/pull/424/files

PreMailer.Net will break for anyone who upgrades to 0.9.9. You need to release a new version that targets 0.9.9 to fix this error.

```
System.MissingMethodException: Method not found: ‘Void AngleSharp.Dom.IElement.RemoveAttribute(System.String)’.

at PreMailer.Net.StyleClassApplier.ApplyStyles(IElement domElement, StyleClass clazz)
at PreMailer.Net.StyleClassApplier.ApplyAllStyles(Dictionary`2 elementDictionary)
at PreMailer.Net.PreMailer.MoveCssInline(Boolean removeStyleElements, String ignoreElements, String css, Boolean stripIdAndClassAttributes, Boolean removeComments)
at Newtonsoft.Web.Infrastructure.Email.EmailHelper.Create(ILogger logger, String toAddress, String subject, String htmlBody)
at Newtonsoft.Web.Domain.AccountDomain.<ForgotPassword>d__8.MoveNext()
```

**Comment by martinnormark** [comment]
@JamesNK Thanks for the details on this. [`v1.5.5`](https://github.com/milkshakesoftware/PreMailer.Net/releases/tag/v1.5.5) is [cooking on AppVeyor](https://ci.appveyor.com/project/milkshakesoftware/premailer-net/build/195) and will push to Nu Get when  complete.
