### ISSUE TITLE
New release with AngelSharp

### ISSUE THREAD

**Issue by darrenshrwd** [milkshakesoftware/PreMailer.Net#78]
Using the 1.4.3 release (via nuget) I get the error below, but it looks like it would already be fixed?... because CsQuery is no longer used:

https://github.com/milkshakesoftware/PreMailer.Net/commit/59123748c368659744111fc7932b86bce15a88d0

**...So wondering when next release will be? :-)**

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=CsQuery
  StackTrace:
       at CsQuery.Engine.SelectorEngine.<GetAdjacentElements>b__36(IDomObject item)
       at CsQuery.CQ.<Map>d__10`1.MoveNext()
       at CsQuery.Engine.SelectorEngine.Select(IEnumerable`1 context)
       at CsQuery.CQ.Select(String selector)
       at PreMailer.Net.PreMailer.FindElementsWithStyles(SortedList`2 stylesToApply)
       at PreMailer.Net.PreMailer.MoveCssInline(Boolean removeStyleElements, String ignoreElements, String css, Boolean stripIdAndClassAttributes, Boolean removeComments)
       at PreMailer.Net.PreMailer.MoveCssInline(String html, Boolean removeStyleElements, String ignoreElements, String css, Boolean stripIdAndClassAttributes, Boolean removeComments)
       at EE.AskForReviews.ProgramToAskForReviews.Main(String[] args) in D:\Projects\ExpertEasy\ExpertEasy\MAIN\Source\EE.AskForReviews\ProgramToAskForReviews.cs:line 75
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by martinnormark** [comment]
Could easily have been fixed already via the AngleSharp changes. Before cutting a new release, I need to look further into #77 to make sure it is not a consequence of moving away from CsQuery.

**Comment by darrenshrwd** [comment]
Actually it's likely this is because the template is a copied file from a servicestack sample and includes `razor markdown`, I'll try with a simpler template soon. Sorry will close.

**Comment by martinnormark** [comment]
:+1:
